# travis build configuration for ZeroPilot-SW

language: cpp
sudo: false


matrix:

  include:


    - os: linux # run unit tests on linux
      compiler: gcc
      env: TYPE_OF_BUILD="unit tests" CXX_FLAGS="-std=c++11"
      addons:
        apt:
          packages:
          - ninja-build
          - cmake
      install: # install google test
        - sudo apt-get install libgtest-dev
        - cd /usr/src/gtest
        - sudo cmake CMakeLists.txt
        - sudo make
        - sudo cp *.a /usr/lib
      script:
        - cd $TRAVIS_BUILD_DIR/Autopilot
        - ./Tools/build.bash -c -T


    - os: linux # check if we can build for the target, from linux
      compiler: gcc
      env: TYPE_OF_BUILD="for target" CXX_FLAGS="-std=c++11"
      addons:
        apt:
          packages:
          - ninja-build
          - cmake
      cache:
        directories:
          - $HOME/gcc-arm-none-eabi-7-2017-q4-major
      install:
        - export GCC_DIR=$HOME/gcc-arm-none-eabi-7-2017-q4-major
        - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
        - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
        - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
        - export PATH=$GCC_DIR/bin:$PATH
      script:
        - cd $TRAVIS_BUILD_DIR/Safety
        - ./Tools/build.bash -c
        - cd $TRAVIS_BUILD_DIR/Autopilot
        - ./Tools/build.bash -c


    - os: osx # run unit tests on mac
      compiler: clang
      env: TYPE_OF_BUILD="unit tests" CXX_FLAGS="-std=c++11"
      install: # install google test
        - curl -LO https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        - tar xf release-1.10.0.tar.gz
        - cd googletest-release-1.10.0
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make install
      script:
        - cd $TRAVIS_BUILD_DIR/Autopilot
        - ./Tools/build.bash -c -T


    - os: osx # check if we can build for the target, from mac
      compiler: clang
      env: TYPE_OF_BUILD="for target" CXX_FLAGS="-std=c++11"
      cache:
        directories:
          - $HOME/gcc-arm-none-eabi-7-2017-q4-major
      install:
        - export GCC_DIR=$HOME/gcc-arm-none-eabi-7-2017-q4-major
        - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
        - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-mac.tar.bz2
        - if [ ! -f $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
        - export PATH=$GCC_DIR/bin:$PATH
      script:
        - cd $TRAVIS_BUILD_DIR/Safety
        - ./Tools/build.bash -c
        - cd $TRAVIS_BUILD_DIR/Autopilot
        - ./Tools/build.bash -c


    - os: windows
      env: TYPE_OF_BUILD="for target" CXX_FLAGS="-std=c++11"
      before install:
        - choco upgrade cmake
        - choco upgrade mingw
      install:
        - mkdir $HOME/gcc-arm-none-eabi-7-2017-q4-major
        - cd $HOME/gcc-arm-none-eabi-7-2017-q4-major
        - wget --no-check-certificate https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-win32.zip
        - 7z x gcc-arm-none-eabi-7-2017-q4-major-win32.zip -aoa
        - setx path "%path%;$HOME/gcc-arm-none-eabi-7-2017-q4-major/bin/"
      script:
        - cd $TRAVIS_BUILD_DIR/Safety
        - ./Tools/build.bash -c
        - cd $TRAVIS_BUILD_DIR/Autopilot
        - ./Tools/build.bash -c
